import { useUser } from '../hooks/useUser';
import './global.css';

export const metadata = {
  title: 'Welcome to lua-desk',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await useUser();

  return (
    <html lang="de">
      <body>{children}</body>
    </html>
  );
}
