import LogoutButton from '../components/LogoutButton';
import { useUser } from '../hooks/useUser';
import './global.css';

export const metadata = {
  title: 'Welcome to lua-desk',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await useUser();

  return (
    <html lang="de">
      <body className="flex flex-col">
        <header className="flex justify-between items-center bg-[#f6ebe3] h-12 gap-2 p-2">
          <h1>{metadata.title}</h1>
          <LogoutButton />
        </header>
        <div className="m-2 flex-1">{children}</div>
      </body>
    </html>
  );
}
